server:
  port: 8083

spring:
  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: GATEWAY-INSTANCE